version: "2"
services:
  valheim_server:
    build:
      context: .
      args:
        name: "Trofogol's Valhalla"
        world: "T.Tanium"
        password: "topor"
        public: 1
    image: valheim_server:vanilla
    # not sure about protocol, so both are allowed
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
    restart: always
    volumes:
      - "/mnt/h/portable/valheim-data:/valheim-data"

    # these quotas works in version 2 only (docker-compose.yaml file, not any tool)
    cpu_count: 4
    # total RAM (mem+swap) limit
    memswap_limit: 2g
    
